# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2


defaults: &defaults
  docker:
    - image: circleci/golang:1.10
  working_directory: /go/src/github.com/Dynatrace/dynatrace-oneagent-operator


jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: dep ensure -v
      - run: go test -cover ./...
      - run: ./tmp/build/build.sh
      - persist_to_workspace:
          root: .
          paths:
            - LICENSE
            - tmp/_output/bin/dynatrace-oneagent-operator
            - tmp/build/*

  deploy-snapshot:
    <<: *defaults
    steps:
      - setup_remote_docker
      - run: |
          mkdir -p ~/.docker && chmod 0700 ~/.docker
          touch ~/.docker/config.json && chmod 0600 ~/.docker/config.json
          base64 -d >~/.docker/config.json <<<"$OAO_DOCKER_AUTH"
      - attach_workspace:
          at: .
      - run:
          environment:
            DOCKERFILE: ./tmp/build/Dockerfile
          command: IMAGE=$OAO_IMAGE:snapshot ./tmp/build/docker_build.sh
      - run: docker push $OAO_IMAGE:snapshot

  deploy-release:
    <<: *defaults
    steps:
      - setup_remote_docker
      - run: |
          mkdir -p ~/.docker && chmod 0700 ~/.docker
          touch ~/.docker/config.json && chmod 0600 ~/.docker/config.json
          base64 -d >~/.docker/config.json <<<"$OAO_DOCKER_AUTH"
      - attach_workspace:
          at: .
      - run:
          environment:
            DOCKERFILE: ./tmp/build/Dockerfile
          command: IMAGE=$OAO_IMAGE:$CIRCLE_TAG ./tmp/build/docker_build.sh
      - run: |
          docker push $OAO_IMAGE:$CIRCLE_TAG
          docker tag $OAO_IMAGE:$CIRCLE_TAG $OAO_IMAGE:latest
          docker push $OAO_IMAGE:latest

  deploy-release-rhcc:
    <<: *defaults
    steps:
      - setup_remote_docker
      - run: |
          mkdir -p ~/.docker && chmod 0700 ~/.docker
          touch ~/.docker/config.json && chmod 0600 ~/.docker/config.json
          base64 -d >~/.docker/config.json <<<"$OAO_DOCKER_AUTH_RHCC"
      - attach_workspace:
          at: .
      - run:
          environment:
            DOCKERFILE: ./tmp/build/Dockerfile-rhel
          command: IMAGE=$OAO_IMAGE_RHCC:$CIRCLE_TAG ./tmp/build/docker_build.sh
      - run: docker push $OAO_IMAGE_RHCC:$CIRCLE_TAG


workflows:
  version: 2
  build-release:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - deploy-snapshot:
          requires:
            - build
          filters:
            branches:
              only: /^master$/
      - deploy-release:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - deploy-release-rhcc:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
